### ISSUE TITLE
My computer cannot render the font Vegur well

### ISSUE THREAD

**Issue by Bial109** [railmapgen/railmapgen.github.io#220]
As written in the title, my computer cannot render the Vegur font in the rail map, however my phone can render it well and my phone can render the font correctly in rail map.

![Image](https://github.com/user-attachments/assets/432ac3ee-e296-4fe7-b90a-bba1f9759f43)

**Comment by thekingofcity** [comment]
This known issue has been resolved and the fix will be included in our release on the first of next month. If you require the fix immediately, please let me know your operating system, and I can prepare a custom build for you.

**Comment by Bial109** [comment]
let me clarify, is the release on today? but I still do not see any fix

btw this is my operating system (In traditional Chinese):
版本	Windows 11 家用版
版本	24H2
安裝於	‎2/‎10/‎2024
OS 組建	26100.4202
體驗	Windows 功能體驗套件 1000.26100.107.0

**Comment by thekingofcity** [comment]
嗨，抱歉新版本没有及时更新，现在您可以在以下的链接中获得：

https://github.com/railmapgen/app/releases/tag/tauri-20250601

另外，部分字体仍然有些问题，我们正在持续修复，也欢迎您报告除了已经修复的Vegur字体外的其他字体问题 :)
